# Generated by Django 2.2.4 on 2019-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freegio', '0008_auto_20190817_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='launches',
            name='Launch_site',
            field=models.TextField(null=True),
        ),
    ]
